#!/bin/csh
foreach size ( 5 10 25 50 100 200 400 800 1000 )
    foreach count ( 5 10 25 50 100 200 400 800 1000 )
        gcc -DNUMS=$size -DNUMT=$count -o hw1 cs475hw1.c -lm -fopenmp -std=c99
        ./hw1 
    end
end